name: food-security
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - geopandas
  - rasterio
  - xarray
  - openpyxl
  - pytest
  - osmnx
  - pip:
      - foastat
      - tomli
      - rasterstats
