[main]
year = 2016
output_path = "./output"
country = "Viet Nam"


[area.region]
path = ""

[area.provinces]
path = ""

[food_production.lifestock.paths]
buffalo = "P:/wflow_global/hydromt/socio_economic/glw/5_Bf_2010_Da.tif"
chicken = "P:/wflow_global/hydromt/socio_economic/glw/5_Ch_2010_Da.tif"
cattle = "P:/wflow_global/hydromt/socio_economic/glw/5_Ct_2010_Da.tif"
duck = "P:/wflow_global/hydromt/socio_economic/glw/5_Dk_2010_Da.tif"
goat = "P:/wflow_global/hydromt/socio_economic/glw/5_Gt_2010_Da.tif"
pig = "P:/wflow_global/hydromt/socio_economic/glw/5_Pg_2010_Da.tif"
horse = "P:/wflow_global/hydromt/socio_economic/glw/5_Ho_2010_Da.tif"

[food_production.rice_yield]
path = "C:/Users/jong/Projects/Food-Security-data/rice_yield/RIB_CULT_prod.his"

[food_production.other_crops]
join_column = "provinces"

[food_production.other_crops.paths]
sea_fish = "C:/Users/jong/Projects/Food-Security-data/other_crops/E06.64.csv"
oranges = "C:/Users/jong/Projects/Food-Security-data/other_crops/E06.40.csv"
peanuts = "C:/Users/jong/Projects/Food-Security-data/other_crops/E06.35.csv"
sugar_cane = "C:/Users/jong/Projects/Food-Security-data/other_crops/E06.33.csv"
cassava = "C:/Users/jong/Projects/Food-Security-data/other_crops/E06.31.csv"
sweet_potatoes = "C:/Users/jong/Projects/Food-Security-data/other_crops/E06.29.csv"
maize = "C:/Users/jong/Projects/Food-Security-data/other_crops/E06.27.csv"



[food_production.aqua_culture]
path = ""
file_type = "vector"

[food_supply.import_export_table]
path = "C:/Users/jong/Projects/Food-Security-data/import_export/FAOSTAT_data_import_export_11-18-2024.csv"

[food_supply.total_production_FAO]
path = "C:/Users/jong/Projects/Food-Security-data/FOA_STAT_food_production.csv"

[food_supply.FAO_item_mapping]
path = "C:/Users/jong/Projects/Food-Security/data/FAO_item_mapping.csv"

[food_transfer_coefficient.GDP_per_capita_per_area]
path = "" 
file_type = "grid"

[food_transfer_coefficient.road_density]
path = ""
file_type = "vector"

[caloric_demand]
demand = 2800

[caloric_demand.population]
path = ""
file_type = "grid"

[nutritional_value_per_crop]
path = ""
file_type = "table"

