[main]
year = 2016
output_path = "./output"
country = "Viet Nam"
country_area = 0    # Country area should be in km2
country_gdp = 0

[area.region]
path = ""

[area.provinces]
path = ""

[food_production.modelled_crops]
rice = "C:/Users/jong/Projects/Food-Security-data/rice_yield/RIB_CULT_prod.his"

[food_production.other_crops]
# If not given crop data is pulled from FAO
path = ""
region_column = "" 

[food_production.fao]
conversion_table = ""


[food_security_data_table]
path = ""

[food_value_table]
path = ""

[caloric_demand]
demand = 2800

