[output]
path = "./output"

[region]
path = ""

[provinces]
path = ""

[food_production.lifestock]
paths = {
    buffaloe = "P:/wflow_global/hydromt/socio_economic/glw/5_Bf_2010_Da.tif"
    chicken = "P:/wflow_global/hydromt/socio_economic/glw/5_Ch_2010_Da.tif"
    cattle = "P:/wflow_global/hydromt/socio_economic/glw/5_Ct_2010_Da.tif
    duck = "P:/wflow_global/hydromt/socio_economic/glw/5_Dk_2010_Da.tif"
    goat = "P:/wflow_global/hydromt/socio_economic/glw/5_Gt_2010_Da.tif"
    pig = "P:/wflow_global/hydromt/socio_economic/glw/5_Pg_2010_Da.tif
    }

[food_production.rice_yield]
path = ""
file_type = "grid"

[food_production.other_crops]
path = ""
file_type = "vector"

[food_production.aqua_culture]
path = ""
file_type = "vector"

[food_supply.import]
path = ""
file_type = "table"

[food_supply.export]
path = ""
file_type = "table"

[food_transfer_coefficient.GDP_per_capita_per_area]
path = "" 
file_type = "grid"

[food_transfer_coefficient.road_density]
path = ""
file_type = "vector"

[caloric_demand]
demand = 2800

[caloric_demand.population]
path = ""
file_type = "grid"

[nutritional_value_per_crop]
path = ""
file_type = "table"

