[main]
year = 2016
output.path = "./output/results.csv"
country = "Viet Nam"
country_area = 0    # Country area should be in km2
aoi.path = ""



[food_production.modelled_crops.rice]
path = "C:/Users/jong/Projects/Food-Security-data/rice_yield/RIB_CULT_prod.his"
calories = 280 # Calories per 100 gram

[food_production.other_crops]
# If not given crop data is pulled from FAO
path = ""
region_column = "" 

[food_production.fao]
conversion_table = ""


[caloric_demand]
demand = 2800

