[main]
year = 2016
output_path = "./output"
country = "Viet Nam"


[area.region]
path = ""

[area.provinces]
path = ""

[food_production.rice_yield]
path = "C:/Users/jong/Projects/Food-Security-data/rice_yield/RIB_CULT_prod.his"

[food_production.aqua_culture]
path = ""

[food_security_data_table]
path = ""
# column names
region = "name"
gdp ="gdp"
population = "population"
import_coefficient = "import_coeff"
export_coefficient = "export_coeff"

[trade.import]
path = ""

[trade.export]
path = ""


[caloric_demand]
demand = 2800

